
import { GoogleGenAI, Type } from "@google/genai";
import { DetectionRequest, DetectionResponse } from "../types";
import { MOCK_API_KEY } from "../constants";

export class VoiceDetectionService {
  private static ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  static async detect(request: DetectionRequest, apiKey: string): Promise<DetectionResponse> {
    if (apiKey !== MOCK_API_KEY) {
      return {
        status: 'error',
        message: 'Access Denied: Please verify your security key.'
      };
    }

    const supported = ['Tamil', 'English', 'Hindi', 'Malayalam', 'Telugu'];
    if (!supported.includes(request.language)) {
      return {
        status: 'error',
        message: 'Language not currently supported by our verification engine.'
      };
    }

    try {
      const model = this.ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: [
          {
            parts: [
              {
                inlineData: {
                  mimeType: 'audio/mp3',
                  data: request.audioBase64
                }
              },
              {
                text: `Analyze this ${request.language} audio recording.
                Your goal is to determine if the voice is a real person or generated by an AI system.
                
                Please look for:
                - Natural human breathing and mouth sounds (real people do this).
                - Subtle emotional changes or slight pitch variations (AI is often too perfect).
                - Robotic flatness or strange "metallic" echoes in the background.
                
                STRICT RESPONSE RULES:
                1. classification MUST be either "AI_GENERATED" or "HUMAN".
                2. confidenceScore MUST be a number between 0.0 and 1.0.
                3. explanation MUST be a natural, friendly description of what you found. Avoid overly robotic technical jargon.
                
                JSON Schema:
                {
                  "status": "success",
                  "language": "${request.language}",
                  "classification": "AI_GENERATED" | "HUMAN",
                  "confidenceScore": number,
                  "explanation": "string"
                }`
              }
            ]
          }
        ],
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              status: { type: Type.STRING },
              language: { type: Type.STRING },
              classification: { type: Type.STRING, enum: ["AI_GENERATED", "HUMAN"] },
              confidenceScore: { type: Type.NUMBER },
              explanation: { type: Type.STRING }
            },
            required: ["status", "language", "classification", "confidenceScore", "explanation"]
          }
        }
      });

      const response = await model;
      return JSON.parse(response.text || "{}") as DetectionResponse;
    } catch (error) {
      console.error("Analysis Failure:", error);
      return {
        status: 'error',
        message: 'We encountered a hiccup while analyzing the audio. Please try again.'
      };
    }
  }
}
