const express = require('express');
const bodyParser = require('body-parser');
const { GoogleGenAI, Type } = require('@google/genai');

const app = express();
app.use(bodyParser.json({ limit: '25mb' }));

const PORT = process.env.PORT || 3000;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const MOCK_API_KEY = process.env.MOCK_API_KEY || 'sk_test_123456789';

if (!GEMINI_API_KEY) {
  console.warn('Warning: GEMINI_API_KEY is not set. Requests will fail until you set this env var.');
}

const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });

app.post('/api/voice-detection', async (req, res) => {
  const { request, apiKey } = req.body || {};
  if (apiKey !== MOCK_API_KEY) {
    return res.status(403).json({ status: 'error', message: 'Access Denied: Please verify your security key.' });
  }

  const supported = ['Tamil', 'English', 'Hindi', 'Malayalam', 'Telugu'];
  if (!request || !supported.includes(request.language)) {
    return res.status(400).json({ status: 'error', message: 'Language not currently supported by our verification engine.' });
  }

  try {
    const model = ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: [
        {
          parts: [
            {
              inlineData: {
                mimeType: 'audio/mp3',
                data: request.audioBase64
              }
            },
            {
              text: `Analyze this ${request.language} audio recording.\nYour goal is to determine if the voice is a real person or generated by an AI system.\n\nPlease look for:\n- Natural human breathing and mouth sounds (real people do this).\n- Subtle emotional changes or slight pitch variations (AI is often too perfect).\n- Robotic flatness or strange "metallic" echoes in the background.\n\nSTRICT RESPONSE RULES:\n1. classification MUST be either "AI_GENERATED" or "HUMAN".\n2. confidenceScore MUST be a number between 0.0 and 1.0.\n3. explanation MUST be a natural, friendly description of what you found. Avoid overly robotic technical jargon.\n\nJSON Schema:\n{\n  "status": "success",\n  "language": "${request.language}",\n  "classification": "AI_GENERATED" | "HUMAN",\n  "confidenceScore": number,\n  "explanation": "string"\n}`
            }
          ]
        }
      ],
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            status: { type: Type.STRING },
            language: { type: Type.STRING },
            classification: { type: Type.STRING, enum: ['AI_GENERATED', 'HUMAN'] },
            confidenceScore: { type: Type.NUMBER },
            explanation: { type: Type.STRING }
          },
          required: ['status', 'language', 'classification', 'confidenceScore', 'explanation']
        }
      }
    });

    const response = await model;
    const parsed = JSON.parse(response.text || '{}');
    return res.json(parsed);
  } catch (err) {
    console.error('Server analysis error:', err);
    return res.status(500).json({ status: 'error', message: 'We encountered a hiccup while analyzing the audio. Please try again.' });
  }
});

app.listen(PORT, () => {
  console.log(`Voice detection server listening on port ${PORT}`);
});
